imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $tables: '%tables%'			
            $ext_images_path: '%core.root_path%ext/david63/movedisapproved/adm/style/images'
        public: true			

    david63.movedisapproved.listener:
        class: david63\movedisapproved\event\listener
        tags:
            - { name: event.listener }

    david63.movedisapproved.main.controller:
        class: david63\movedisapproved\controller\main_controller

    david63.movedisapproved.admin.controller:
        class: david63\movedisapproved\controller\admin_controller

    david63.movedisapproved.core.functions:
        class: david63\movedisapproved\core\functions
